Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  SERVERS = 5
  BRIDGE = "InternalSwitch" 

  def create_host(config, hostname, ip)
    config.vm.define hostname do |host|
      host.vm.network "private_network", type: "dhcp"
      host.vm.network "public_network", bridge: BRIDGE

      host.vm.provider "hyperv" do |h|
        h.memory = 2048
        h.cpus = 2
      end

      host.vm.hostname = hostname

      host.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y python3-minimal
      SHELL
    end
  end

  (1..SERVERS).each do |machine_id|
    create_host(config, "srv#{machine_id}", "169.254.217.#{200 + machine_id}")
  end
end
