---
roles:
  - name: docker
    src: https://gitlab.com/morcherlfy/infratructureascode-ansible-roles/docker.git
    scm: git
    path: docker

  - name: nginx
    src: https://gitlab.com/morcherlfy/infratructureascode-ansible-roles/nginx.git
    scm: git
    path: nginx