---
roles:
  - name: docker_deploy
    src: https://github.com/MorCherlf/InfrastructureAsCode-Ansible-Roles.git
    scm: git

  - name: api_deploy
    src: https://github.com/MorCherlf/InfrastructureAsCode-Ansible-Roles.git
    scm: git

  - name: prometheus
    src: https://github.com/MorCherlf/InfrastructureAsCode-Ansible-Roles.git
    scm: git

  - name: loki
    src: https://github.com/MorCherlf/InfrastructureAsCode-Ansible-Roles.git
    scm: git

  - name: grafana
    src: https://github.com/MorCherlf/InfrastructureAsCode-Ansible-Roles.git
    scm: git

  - name: prometheus_email_alert
    src: https://github.com/MorCherlf/InfrastructureAsCode-Ansible-Roles.git
    scm: git
