---
roles:
  - name: docker_deploy
    src: https://gitlab.com/morcherlfy/infratructureascode-ansible-roles/docker_deploy.git
    scm: git

  - name: api_deploy
    src: https://gitlab.com/morcherlfy/infratructureascode-ansible-roles/api_deploy.git
    scm: git

  - name: prometheus
    src: https://gitlab.com/morcherlfy/infratructureascode-ansible-roles/prometheus.git
    scm: git

  - name: loki
    src: https://gitlab.com/morcherlfy/infratructureascode-ansible-roles/loki.git
    scm: git

  - name: grafana
    src: https://gitlab.com/morcherlfy/infratructureascode-ansible-roles/grafana.git
    scm: git

  - name: prometheus_email_alert
    src: https://gitlab.com/morcherlfy/infratructureascode-ansible-roles/prometheus_email_alert.git
    scm: git
